name: Terraform

on: [push]

jobs:
  terraform-localstack:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform LocalStack
      uses: ShubhamTatvamasi/terraform-localstack-action@master

  terraform-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Lint
      uses: ShubhamTatvamasi/terraform-lint-action@master
